# Generated by Django 4.0.2 on 2022-02-21 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contect',
            new_name='Contact',
        ),
    ]
